3F/Controllers/API/AdministraceController.cs
using System.Linq;
using System.Web.Http;
using _3F.Model;
using _3F.Model.Model;
using _3F.Web.Definitions;

namespace _3F.Web.Controllers.API
{
    public class AdministraceController : BaseApiController
    {

        public AdministraceController(IRepository repository)
            : base(repository)
        {
        }

        [HttpGet, Authorize(Roles= "Administrator,Council,Supervisor")]
        public IHttpActionResult Uzivatele()
        {
            var model = repository.All<AspNetUsers>()
                .ToArray()
                .Select(u => new [] 
                {
                    u.Id.ToString(), 
                    u.UserName, u.Email, 
                    u.DateCreated.ToString(Strings.DateFormat), 
                    u.LoginType.ToString(),
                    u.Profile_Id.ToString(), 
                    u.VariableSymbol?.ToString() ?? "",
                    u.DateLastActivity.ToString(Strings.DateFormat),
                }).ToArray();

            return Ok(new { data = model });
        }

        [HttpGet, Authorize(Roles = "Administrator")]
        public IHttpActionResult Akce()
        {
            var model = repository.All<Event>()
                .ToArray()
                .Select(u => new []
                {
                    u.Id.ToString(),
                    u.Name,
                    u.StartDateTime.ToString(Strings.DateFormat),
                    u.EventType.ToString(),
                    u.State.ToString(),
                    u.HtmlName,
                }).ToArray();

            return Ok(new { data = model });
        }
    }
}

3F/Controllers/AdministraceController.cs
using System.Net;
using _3F.Model.Service;

namespace _3F.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Reflection;
    using System.Threading.Tasks;
    using System.Web;
    using System.Web.Mvc;
    using _3F.Model;
    using _3F.Model.Accounting;
    using _3F.Model.Email;
    using _3F.Model.Email.Model;
    using _3F.Model.Extensions;
    using _3F.Model.Model;
    using _3F.Model.Repositories;
    using _3F.Model.Repositories.Interface;
    using _3F.Model.Utils;
    using _3F.Web.Definitions;
    using _3F.Web.Helpers;
    using _3F.Web.Models;
    using _3F.Web.Models.Administration;
    using _3F.Web.Utils;
    using Microsoft.AspNet.Identity;
    using Post = BusinessEntities.Post;

    [Authorize(Roles = "Administrator,Council,Supervisor")]
    public class AdministraceController : BaseController
    {
        private const string PostFileManagerPath = "~/App_Data/PostUpload";
        private readonly ApplicationUserManager userManager;
        private readonly ILogToEvent logToEvent;
        private readonly IAccounting accounting;
        private readonly IEmailSender emailSender;
        private readonly IHelpRepository helpRepository;
        private readonly IEventCategoryRepository eventCategoryRepository;
        private readonly IPostRepository postRepository;
        private readonly IFileUploadInfoRepository fileUploadInfoRepository;
        private readonly IKnowFromRepository knowFromRepository;
        private readonly IOrganizationMembersRepository organizationMembersRepository;
        private readonly IMessageService messageService;
        private readonly IRajceService rajceService;
        private readonly IEventUtils eventUtils;

        private readonly string[] roleForCouncil =
        {
            "Accountant", "EventCreator", "BadmintonAdmin", "BadmintonUser",
            "CertifiedOrganisator", "PrivateOrganisator", "Council", "Supervisor", "Chief"
        };

        public AdministraceController(
            ApplicationUserManager userManager, 
            ILogToEvent logToEvent,
            IAccounting accounting, 
            IEmailSender emailSender, 
            IHelpRepository helprepository,
            IEventCategoryRepository eventCategoryrepository, 
            IPostRepository postrepository, 
            IFileUploadInfoRepository fileUploadrepository,
            IKnowFromRepository knowFromrepository, 
            IOrganizationMembersRepository organizationMembersrepository,
            IMessageService messageService,
            IRajceService rajceService,
            IEventUtils eventUtils)
        {
            this.userManager = userManager;
            this.logToEvent = logToEvent;
            this.accounting = accounting;
            this.emailSender = emailSender;
            this.helpRepository = helprepository;
            this.eventCategoryRepository = eventCategoryrepository;
            this.postRepository = postrepository;
            this.fileUploadInfoRepository = fileUploadrepository;
            this.knowFromRepository = knowFromrepository;
            this.organizationMembersRepository = organizationMembersrepository;
            this.messageService = messageService;
            this.rajceService = rajceService;
            this.eventUtils = eventUtils;
            this.BackgroundColor = "dark-background";
            this.Icon = "icon-cogs";
        }

        public ActionResult Index()
        {
            Assembly assembly = Assembly.GetExecutingAssembly();
            FileInfo fileInfo = new FileInfo(assembly.Location);
            string time = fileInfo.LastWriteTime.ToString("dd.MM.yyyy HH:mm");
            ViewBag.IsAdmin = User.IsInRole(Strings.Administrator);

            return this.View(new EmptyBaseViewModel() { Title = $"Administrace (verze {time})" });
        }

        #region Logy
        public ActionResult Logy(string id, string typ)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                string[] files = Directory.GetFiles(Server.MapPath("~/Logs"), "*.log*");
                Array.Sort(files, (u, v) => string.Compare(v, u, StringComparison.Ordinal));
                var logNameList = files.Select(f => new LogName(f));
                return this.View("LogList", logNameList);
            }
            else
            {
                string logName = id + ".log";
                if (!string.IsNullOrWhiteSpace(typ))
                {
                    logName = logName + typ;
                }
                
                if (System.IO.File.Exists(Server.MapPath("~/Logs") + "/" + logName))
                {
                    var lines = System.IO.File.ReadAllLines(Server.MapPath("~/Logs") + "/" + logName, System.Text.Encoding.UTF8);
                    if (string.IsNullOrWhiteSpace(typ))
                    {
                        List<LogUnit> items = new List<LogUnit>();
                        for (int i = 0; i < lines.Length; i++)
                        {
                            if (lines[i].Split(new[] { ";" }, StringSplitOptions.None).Length < 3)
                            {
                                items.Add(new LogUnit(lines[i] + lines[i + 1]));
                                i++;
                            }
                            else
                            {
                                items.Add(new LogUnit(lines[i]));
                            }
                        }

                        ViewBag.Title = logName;
                        return this.View("LogDetail", items);
                    }
                    else
                    {
                        return this.View("LogComplete", lines);
                    }
                }
                else
                {
                    return this.View("LogDetail", new List<LogUnit>());
                }
            }
        }
        #endregion

        #region Přehled uživatelů
        public ActionResult PrehledUzivatelu()
        {
            return this.View(new EmptyBaseViewModel("Přehled uživatelů"));
        }
        #endregion

        #region Přehled pravidelných akcí
        public ActionResult PrehledPravidelnychAkci()
        {
            var result = repository.All<PeriodicEvent>()
                .ToArray()
                .Select(pe => new[]
                {
                    pe.Id.ToString(),
                    pe.EventNameFormat,
                    pe.PeriodicEventType.ToString(),
                    this.GetParameterString(pe),
                });

            return this.View(result);
        }

        private string GetParameterString(PeriodicEvent periodicEvent)
        {
            if (periodicEvent.PeriodicEventType == PeriodicEventTypeEnum.DayInWeek)
            {
                return DateTimeFormatInfo.CurrentInfo.GetDayName((DayOfWeek)periodicEvent.PeriodicParameter);
            }

            return periodicEvent.PeriodicParameter.ToString();
        }
        #endregion

        #region Nastavení práv uživatelů
        public ActionResult Uzivatele()
        {
            var model = repository.Where<AspNetUsers>(u => u.LoginType == LoginTypeEnum.Confirmed || u.LoginType == LoginTypeEnum.OldSystemConfirmed)
                .OrderBy(u => u.UserName)
                .Select(u => new UserWithRoles()
                {
                    htmlName = u.HtmlName,
                    name = u.UserName,
                    ProfilePhoto = u.ProfilePhoto,
                })
                .ToArray();

            return this.View(model);
        }

        public ActionResult Uzivatel(string id)
        {
            var user = repository.OneByHtml<AspNetUsers>(id);

            var model = new GenericBaseViewModel<UserWithRoles>(new UserWithRoles()
            {
                htmlName = user.HtmlName,
                name = user.UserName,
                ProfilePhoto = user.ProfilePhoto,
                Email = user.Email,
            })
            {
                Title = "Nastavení uživatele " + user.UserName
            };

            foreach (var roleName in Enum.GetNames(typeof(RolesEnum)))
            {
                model.Entity.Roles.Add(new RoleViewModel()
                    {
                        RoleName = roleName,
                        RoleDescription = this.GetRoleDescription(roleName),
                        IsInRole = user.AspNetRoles.Any(r => r.Name == roleName),
                        IsEditable = this.IsRoleEditable(roleName),
                    });
            }

            return this.View(model);
        }

        [HttpPost, ValidateAntiForgeryToken, ActionName("Uzivatel")]
        public async Task<ActionResult> UzivatelPost(string id, string[] roles)
        {
            try
            {
                if (roles == null)
                {
                    roles = new string[] { };
                }

                int userId = repository.One<AspNetUsers>(u => u.HtmlName == id).Id;

                foreach (var roleName in Enum.GetNames(typeof(RolesEnum)))
                {
                    var userInRole = await this.userManager.IsInRoleAsync(userId, roleName);
                    if (roles.Contains(roleName) && !userInRole)
                    {
                        await this.userManager.AddToRoleAsync(userId, roleName);
                    }
                    else if (!roles.Contains(roleName) && userInRole)
                    {
                        await this.userManager.RemoveFromRoleAsync(userId, roleName);
                    }
                }

                this.CreateToastrMessage("Role byly úspěšně nastaveny.");
            }
            catch (Exception ex)
            {
                logger.LogException(ex, "Administrace.UzivatelPost");
                this.CreateToastrMessage("Při nastavování rolí došlo k chybě.");
            }

3F/Controllers/HelpController.cs
using System.Web.Mvc;
using _3F.Model.Repositories;
using _3F.Web.Models;

namespace _3F.Web.Controllers
{
    public class HelpController : BaseController
    {
        private readonly IHelpRepository _repository;

        public HelpController(IHelpRepository repository)
        {
            _repository = repository;
        }

        [Authorize]
        public ActionResult Index()
        {
            var help = _repository.GetAll();
            var model = new EnumerableBaseViewModel<BusinessEntities.Help>(help)
            {
                Title = "Nápověda",
                Icon = "icon-question",
                BackgroundColor = "sea-blue-background",
            };

            return View(model);
        }
    }
}

3F/Controllers/KategorieController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using _3F.Model.Model;
using _3F.Model.Service;
using _3F.Model.Service.Model;
using _3F.Web.Models;
using _3F.Web.Models.Discussion;

namespace _3F.Web.Controllers
{
    public class KategorieController : BaseController
    {
        private IActivityListService activityListService;

        public KategorieController(IActivityListService activityListService)
        {
            BackgroundColor = "sea-background";
            Icon = "icon-question";
            this.activityListService = activityListService;
        }

        [Route("Kategorie/{id}")]
        public ActionResult Index(string id)
        {
            var model = new MainPageModel()
            {
                EventType = EventsType.category,
                Activities = GetActivities(),
                CategoryHtmlName = id,
                CategoryName = repository.OneByHtml<EventCategory>(id).Name,
                Discussion = GetDiscussion(),
            };

            ViewBag.DescriptionIcon = "icon-filter";

            return View("~/Views/Home/Index.cshtml", model);
        }

        [OutputCache(Duration = 300, VaryByParam = "none")]
        private IEnumerable<ActivityModel> GetActivities()
        {
            return activityListService.GetActivities();
        }

        private IEnumerable<DiscussionMainPageModel> GetDiscussion()
        {
            return repository
                .Where<Discussion>(d => d.IsAlone)
                .OrderByDescending(d => d.LastUpdateDate)
                .Take(3)
                .Select(d => new DiscussionMainPageModel()
                {
                    Name = d.Name,
                    HtmlName = d.HtmlName
                });
        }
    }
}

3F/Controllers/PostController.cs
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using _3F.BusinessEntities;
using _3F.Model.Repositories;
using _3F.Model.Repositories.Interface;
using _3F.Web.Models;
using _3F.Web.Models.Administration;
using _3F.Web.Utils;

namespace _3F.Web.Controllers
{
    public class PostController : BaseController
    {
        private readonly ApplicationUserManager _userManager;
        private readonly IPostRepository _postRepository;
        private readonly IOrganizationMembersRepository _organizationMembersRepository;

        public PostController(IPostRepository postRepository, IOrganizationMembersRepository organizationMembersRepository)
        {
            _userManager = DependencyResolver.Current.GetService<ApplicationUserManager>();
            _postRepository = postRepository;
            _organizationMembersRepository = organizationMembersRepository;
        }

        [Route("Post/{id}")]
        public ActionResult Index(string id)
        {
            int numId;
            var entity = (int.TryParse(id, out numId)) ? _postRepository.GetById(numId) : _postRepository.GetByHtml(id);

            if (!UserHasViewAccess(entity))
            {
                return View("~/Views/Text/NoRights.cshtml", new EmptyBaseViewModel("Nedostatečná práva"));
            }

            var model = new TextViewModel()
            {
                Key = entity.HtmlName,
                Text = entity.Content,
                Title = entity.Name,
                Icon = entity.Icon,
            };

            if (UserHasEditAccess(entity))
            {
                model.AddActionButton("Editovat", Utilities.Url("~/Text/Edit/" + entity.HtmlName), "icon-edit");
            }

            var viewModel = new GenericBaseViewModel<PostViewModel>(new PostViewModel(entity))
            {
                Title = entity.Name,
                BackgroundColor = "brown-background",
            };

            return View(viewModel);
        }

        private bool UserHasViewAccess(Post entity)
        {
            if (entity == null)
                return false;

            if (string.IsNullOrEmpty(entity.ViewPermissions))
                return true;

            if (!User.Identity.IsAuthenticated)
            {
                return false;
            }

            var permissions = entity.ViewPermissions.Split(',');

            // hvězdička -> přístupné pro všechny přihlášené uživatele
            if (permissions.Contains("*"))
                return true;

            // procento -> přístupné pouze členům
            if (permissions.Contains("%"))
            {
                if (_organizationMembersRepository.IsMember(GetUserId))
                    return true;
            }

            // není hvězdička -> zkontrolovat role a jména
            var roles = _userManager.GetRoles(GetUserId);

            return (permissions.Intersect(roles).Any() || permissions.Contains(User.Identity.Name));
        }

        private bool UserHasEditAccess(Post entity)
        {
            if (!User.Identity.IsAuthenticated)
                return false;

            var permissions = entity.EditPermissions.Split(',');
            var roles = _userManager.GetRoles(GetUserId);

            if (permissions.Contains("%") && _organizationMembersRepository.IsMember(GetUserId))
                return true;

            return (permissions.Intersect(roles).Any() || permissions.Contains(User.Identity.Name));
        }
    }
}

3F/Views/Administrace/AddPhotoAlbum.cshtml
@model _3F.Web.Models.GenericBaseViewModel<_3F.Web.Models.Administration.AddPhotoAlbum>

@{
    Layout = "~/Views/Shared/_FullPageLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

    <div>
        @Html.Label("HtmlName", "Vyber akci:")
        @Html.DropDownList("HtmlName", Model.Entity.Events)
    </div>
    <br />
    <div>
        @Html.Label("UserName", "Vyber uživatele:")
        @Html.DropDownList("UserName", Model.Entity.Users)
    </div>
    <br />
    <div>
        @Html.Label("Link", "Odkaz na fotoalbum na rajceti:")
        @Html.TextBox("Link", Model.Entity.Link)
    </div>
    <br />

    <input type="submit" value="Vložit fotoalbum" />
}

3F/Views/Administrace/EventBalanceOverView.cshtml
@model _3F.Web.Models.EnumerableBaseViewModel<_3F.Web.Models.Administration.EventBalance>

@{
    ViewBag.Title = "Finanční bilance akcí";
    Layout = "~/Views/Shared/_FullPageLayout.cshtml";
}

<table class="table">
    <tr>
        <th>
            Název
        </th>
        <th>
            Datum akce
        </th>
        <th>
            Organizátoři
        </th>
        <th>
            Cena akce
        </th>
        <th>
            Kapacita
        </th>
        <th>
            Celkové náklady
        </th>
        <th>
            Dosud vybráno
        </th>
        <th>
            Dosud nezaplaceno
        </th>
        <th>
            Aktuální bilance
        </th>
        <th>
            Výhledová bilance
        </th>
        <th>
            Popis nákladů
        </th>
    </tr>

    @foreach (var item in Model.Entities)
    {
        <tr>
            <td>
                <a href='@Url.Content("~/Akce/Detail/" + item.HtmlName)' >@item.Name</a>
            </td>
            <td>
                @item.StartDate
            </td>
            <td>
                @item.Organisators
            </td>
            <td>
                @item.Price
            </td>
            <td>
                @item.Capacity
            </td>
            <td>
                @item.Costs.ToString("C0")
            </td>
            <td>
                @item.Paid.ToString("C0")
            </td>
            <td>
                @item.WillBePaid.ToString("C0")
            </td>
            <td>
                @((item.Paid - item.Costs).ToString("C0"))
            </td>
            <td>
                @((item.Paid + item.WillBePaid - item.Costs).ToString("C0"))
            </td>
            <td>
                @Html.Raw(item.CostsDescription)
            </td>
        </tr>
    }
</table>

3F/Views/Administrace/Help.cshtml
@model _3F.Web.Models.EnumerableBaseViewModel<_3F.BusinessEntities.Help>

@{
    Layout = "~/Views/Shared/_FullPageLayout.cshtml";
}

<div class="row">
    <div class="btn btn-success roundCorners">
        <i class="icon-plus"> </i> Nová položka
    </div>
</div>
<div class="row">
    <table class="borderTable">
        <thead>
        <tr>
            <th>Id</th>
            <th>Otázka</th>
            <th>Text</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.Entities)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Question</td>
                <td>@Html.Raw(item.Answer)</td>
                <td><div data-id="@item.Id" class="btn btn-warning roundCorners">Editovat</div></td>
            </tr>
        }
        </tbody>
    </table>
</div>

@Html.RenderModalPlaceHolder()

@section Scripts {
    <script type="text/javascript">
        var TeamDetailPostBackURL = '@Url.Content("~/Administrace/HelpEdit/")';
        $(function () {
            $(".roundCorners").click(function () {
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                var options = { "backdrop": "static", keyboard: true };
                $.ajax({
                    type: "GET",
                    url: TeamDetailPostBackURL,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        $('#myModalContent').html(data);
                        $('#myModal').modal(options);
                        $('#myModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
        });
    </script>    
}

3F/Views/Administrace/KategorieDelete.cshtml
@model _3F.BusinessEntities.EventCategory

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title" id="myModalLabel">Smazání kategorie</h4>
</div>
<div class="box-content">
    <div class="box-content box-statistic">
        <h3>Opravdu chcete smazat kategorii "@Model.Name"?</h3>
        <div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <br />
                <input type="submit" value="Smazat" class="btn btn-danger" style="margin-left:10px; margin-right:10px;" />
                <button class="btn btn-success" data-dismiss="modal"  style="margin-left: 10px; margin-right: 10px;">Zpět</button>
            }
        </div>
    </div>
</div>

@Html.FormSubmitWaitDialog()

3F/Views/Administrace/KategorieNova.cshtml
@model _3F.Web.Models.Administration.CategoryEdit

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_FullPageLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

    <div>
        @Html.LabelFor(m => m.Name, "Název nové kategorie:")
        @Html.TextBoxFor(m => m.Name, new { style = "width: 100%;" })
    </div>
    <br />
    <input type="submit" value="Uložit" class="btn btn-danger" />
    <a href='@Url.Action("Kategorie", "Administrace")' class="btn btn-primary">
        Zpět na seznam kategoríí
    </a>
}

3F/Views/Administrace/KategorieSmazat.cshtml
@model _3F.Web.Models.Administration.CategoryEdit

@{
    Layout = "~/Views/Shared/_FullPageLayout.cshtml";
}

<h3>Opravdu chcete smazat kategorii "@Model.Name"?</h3>
<div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <br />
        <input type="submit" value="Smazat" class="btn btn-danger" style="margin-left:10px; margin-right:10px;" />
        <a href='@Url.Action("Kategorie", "Administrace")' class="btn btn-primary">
            Zpět na seznam kategoríí
        </a>
    }
</div>

@Html.FormSubmitWaitDialog()

3F/Views/Administrace/LogList.cshtml
@model IEnumerable<_3F.Web.Models.Administration.LogName>

@{
    ViewBag.Title = "ProgramLog";
}

<div>
    @{
        foreach (var logName in Model)
        {
            <b>
                <a href="@Url.Content("~/Administrace/Logy/" + logName.Name + "?typ=" + logName.Type)">@logName.FullName</a>
            </b>
            <br />
        }
    }
</div>

3F/Views/Administrace/News.cshtml
@model _3F.Web.Models.Administration.NewsViewModel

@{
    Layout = "~/Views/Shared/_FullPageLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })

    <div>
        @Html.LabelFor(m => m.News, "Text novinky:")
        @Html.TextBoxFor(m => m.News, new { style = "width: 100%;" })
    </div>
    <br />
    <input type="submit" value="Uložit" class="btn btn-danger" />
}

3F/Views/Administrace/Nezaplaceno.cshtml
@model _3F.Web.Models.EnumerableBaseViewModel<_3F.Web.Models.Administration.PaymentViewModel>

@{
    Layout = "~/Views/Shared/_FullPageLayout.cshtml";
}

<link rel="stylesheet" href="~/Content/Plugins/datatables/jquery.dataTables.min.css" />

<table id="example" class="display" cellspacing="0"></table>

@section Scripts {
    @Scripts.Render("~/bundles/datatables")

<script type="text/javascript">
        $(document).ready(function () {
            var oTable = $('#example').dataTable({
                "iDisplayLength": 25,
                "columns": [
                    { "title": "Id", "width": "7%", "render": function ( data, type, row, meta ) { return row.Id } },
                    { "title": "Uživatel", "width": "7%", "render": function (data, type, row, meta) { return row.UserName } },
                    { "title": "Akce", "width": "21%", "render": function ( data, type, row, meta ) {
                        return '<a href=@Url.Content("~/Akce/Detail/")'+ row.EventHtml +'>' + row.EventName + '</a>'; } },
                    { "title": "Částka", "width": "6%", "render": function (data, type, row, meta) { return row.Amount } },
                    { "title": "Poznámka", "width": "39%", "render": function (data, type, row, meta) { return row.Note } },
                    { "title": "Vytvořeno", "width": "15%", "render": function (data, type, row, meta) { return row.CreateDate } },
                    { "title": "", "width": "5%", "render": function ( data, type, row, meta ) {
                        return '<a href=@Url.Content("~/Administrace/Zaplatit/")' + row.Id + '>Zaplatit</a>'; } },
                ],
                "data" : @Html.Raw(Json.Encode(Model.Entities)),
            });
        });
</script>
}

3F/Views/Administrace/PostFileManagerUpload.cshtml
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title" id="myModalLabel">Nahrání souboru</h4>
</div>
<div class="box-content">
    <div class="box-content box-statistic">
        @using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                
                <div class="form-group">
                    @Html.Label("Popisek souboru", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="text" name="Description" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("Vložte soubor", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="file" />
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Nahrát soubor" name="submit" class="btn btn-success" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

3F/Views/Administrace/PotvrzovaciEmail.cshtml
@model _3F.Web.Models.GenericBaseViewModel<string>

@{
    Layout = "~/Views/Shared/_FullPageLayout.cshtml";
}

<div class="row">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">

            <div class="form-group">
                @Html.Label("Email uživatele ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.Editor("email", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessage("email", "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Poslat email" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>

3F/Views/Administrace/PrehledPlateb.cshtml
@model _3F.Web.Models.EnumerableBaseViewModel<string[]>

@{
    Layout = "~/Views/Shared/_FullPageLayout.cshtml";
}

<link rel="stylesheet" href="~/Content/Plugins/datatables/jquery.dataTables.min.css" />

<table id="example" class="display" cellspacing="0"></table>

@section Scripts {
    @Scripts.Render("~/bundles/datatables")

    <script type="text/javascript">
    $(document).ready(function () {
        var oTable = $('#example').dataTable({
            "iDisplayLength": 25,
            "columns": [
                { "title": "Id" },
                { "title": "Uživatel" },
                { "Title": "VS" },
                { "title": "Status" },
                { "title": "Částka" },
                { "title": "Vytvořeno", "type": "cz_datetime" },
                { "title": "Updatováno", "type": "cz_datetime" },
                { "title": "Poznámka" },
                { "title": "", "render": function ( data, type, full, meta ) {
                    return '<a href=@Url.Content("~/Administrace/ChangePayment/")'+data+'>Upravit</a>'; }
                },
            ],
            "order": [[ 0, "desc" ]],
            "data" : @Html.Raw(Json.Encode(Model.Entities)),
        });
    });
    </script>
}

3F/Views/Administrace/PrehledRoli.cshtml
@model IEnumerable<_3F.Web.Models.Administration.RoleWithUsers>

@{
    ViewBag.Title = "Přehled rolí";
}

<div class="row">
    <div class="col-md-12">
        <div class="box box-nomargin">
            <div class="box-header dark-background">
                <i class="icon-cogs"> </i>Přehled rolí
            </div>
            <div class="box-content" style="background-color:#f4f4f4;">
                @foreach (var role in Model)
                {
                    <div class="box-content box-statistic">
                        <h3>@role.Name (@role.Users.Count())</h3>
                        @Html.Partial("~/Views/Shared/_Users.cshtml", role.Users)
                    </div>
                }
            </div>
        </div>
    </div>
</div>